### ISSUE TITLE
Cannot find module 'eslint-config-tslint-config-airbnb'

### ISSUE THREAD

**Issue by strelov1** [progre/tslint-config-airbnb#43]
My [eslint](https://github.com/strelov1/lim/blob/master/.eslintrc.yml) 
eslint -c .eslintrc.yml ./src

I got error

> Cannot find module 'eslint-config-tslint-config-airbnb'
Referenced from: /home/user/Project/lim/.eslintrc.yml
Error: Cannot find module 'eslint-config-tslint-config-airbnb'
Referenced from: /home/user/Project/lim/.eslintrc.yml
    at ModuleResolver.resolve (/home/user/Project/lim/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/home/user/Project/lim/node_modules/eslint/lib/config/config-file.js:479:28)
    at load (/home/user/Project/lim/node_modules/eslint/lib/config/config-file.js:551:26)
    at configExtends.reduceRight (/home/user/Project/lim/node_modules/eslint/lib/config/config-file.js:425:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/home/user/Project/lim/node_modules/eslint/lib/config/config-file.js:403:26)
    at loadFromDisk (/home/user/Project/lim/node_modules/eslint/lib/config/config-file.js:523:22)
    at Object.load (/home/v/Project/lim/node_modules/eslint/lib/config/config-file.js:559:20)
    at Config.loadSpecificConfig (/home/user/Project/lim/node_modules/eslint/lib/config.js:135:46)
    at new Config (/home/user/Project/lim/node_modules/eslint/lib/config.js:101:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lim@0.1.0 lint: `eslint -c .eslintrc.yml ./src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lim@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-06-19T09_15_26_845Z-debug.log

**Comment by Darep** [comment]
You need to remove eslint and install [tslint](https://github.com/palantir/tslint) if you want to use this config :)

If you want airbnb config with eslint, try `extends: 'airbnb'` and install this: https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

**Comment by strelov1** [comment]
Oh, I've got it all mixed up. Thank you
